-- MySQL Script generated by MySQL Workbench
-- Mon May 24 00:15:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estudo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudo` DEFAULT CHARACTER SET utf8 ;
USE `estudo` ;

-- -----------------------------------------------------
-- Table `estudo`.`TB_PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`TB_PAIS` (
  `ID_PAIS` INT NOT NULL,
  `NM_PAIS` VARCHAR(45) NOT NULL,
  `NR_POPULACAO` INT NOT NULL,
  PRIMARY KEY (`ID_PAIS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`TB_EQUIPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`TB_EQUIPE` (
  `ID_EQUIPE` INT NOT NULL,
  `NM_EQUIPE` VARCHAR(45) NOT NULL,
  `ID_PAIS_EQ_(FK)` INT NOT NULL,
  PRIMARY KEY (`ID_EQUIPE`, `ID_PAIS_EQ_(FK)`),
  CONSTRAINT `ID_PAIS_FQ_(FK)`
    FOREIGN KEY (`ID_PAIS_EQ_(FK)`)
    REFERENCES `estudo`.`TB_PAIS` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`TB_PILOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`TB_PILOTO` (
  `ID_PILOTO` INT NOT NULL,
  `NM_PILOTO` VARCHAR(45) NOT NULL,
  `DT_NASCIMENTO` DATE NOT NULL,
  `ID_PAIS_PI_(FK)` INT NOT NULL,
  `ID_EQUIPE_PI_(FK)` INT NOT NULL,
  PRIMARY KEY (`ID_PILOTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`),
  CONSTRAINT `ID_PAIS(FK)`
    FOREIGN KEY (`ID_PAIS_PI_(FK)`)
    REFERENCES `estudo`.`TB_PAIS` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_EQUIPE(FK)`
    FOREIGN KEY (`ID_EQUIPE_PI_(FK)`)
    REFERENCES `estudo`.`TB_EQUIPE` (`ID_EQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`TB_CIRCUITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`TB_CIRCUITO` (
  `ID_CIRCUITO` INT NOT NULL,
  `NM_CIRCUITO` VARCHAR(45) NOT NULL,
  `NR_EXTENSAO` INT NOT NULL,
  `ID_PAIS_CI_(FK)` INT NOT NULL,
  PRIMARY KEY (`ID_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`),
  CONSTRAINT `ID_PAIS_CI_(FK)`
    FOREIGN KEY (`ID_PAIS_CI_(FK)`)
    REFERENCES `estudo`.`TB_PAIS` (`ID_PAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`TB_PROVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`TB_PROVA` (
  `ID_PROVA` INT NOT NULL,
  `DT_PROVA` INT NOT NULL,
  `NM_SITUACAO` VARCHAR(45) NOT NULL,
  `ID_CIRCUITO_PR_(FK)` INT NOT NULL,
  PRIMARY KEY (`ID_PROVA`, `ID_CIRCUITO_PR_(FK)`),
  CONSTRAINT `ID_CIRCUITO(FK)`
    FOREIGN KEY (`ID_CIRCUITO_PR_(FK)`)
    REFERENCES `estudo`.`TB_CIRCUITO` (`ID_CIRCUITO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`TB_RESULTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`TB_RESULTADO` (
  `ID_PROVA_RE_(FK)` INT NOT NULL,
  `ID_PILOTO_RE_(FK)` INT NOT NULL,
  `NR_TEMPO_PROVA` TIME NOT NULL,
  `NR_COLECAO_FINAL` INT NOT NULL,
  `NR_MELHOR_VOLTA` TIME NOT NULL,
  `NR_POSICAO_GRID` INT NOT NULL,
  PRIMARY KEY (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`),
  CONSTRAINT `ID_PILO(FK)`
    FOREIGN KEY (`ID_PILOTO_RE_(FK)`)
    REFERENCES `estudo`.`TB_PILOTO` (`ID_PILOTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PROVA(FK)`
    FOREIGN KEY (`ID_PROVA_RE_(FK)`)
    REFERENCES `estudo`.`TB_PROVA` (`ID_PROVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
CREATE TABLE IF NOT EXISTS `estudo`.`TB_CIRCUITO` (   `ID_CIRCUITO` INT NOT NULL,   `NM_CIRCUITO` VARCHAR(45) NOT NULL,   `NR_EXTENSAO` INT NOT NULL,   `ID_PAIS_CI_(FK)` INT NOT NULL,   PRIMARY KEY (`ID_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`),   CONSTRAINT `ID_PAIS(FK)`     FOREIGN KEY (`ID_PAIS_CI_(FK)`)     REFERENCES `estudo`.`TB_PAIS` (`ID_PAIS`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB
