/*
 1 ------INSERINDO DADOS NA TABELA PAIS-------
 */
 
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('30', 'FINLÂNDIA', '5540720');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('31', 'MÔNACO', '39242');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('32', 'REINO UNIDO', '67886011');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('33', 'REINO UNIDO', '67886011');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('34', 'ESPANHA', '46754778');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('35', 'MEXICO', '128932753');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('36', 'FRANÇA', '65273511');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('37', 'FRANCA', '65273511');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('38', 'ITALIA', '60461826');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('39', 'ALEMANHA', '83783942');
INSERT INTO `estudo`.`tb_pais` (`ID_PAIS`, `NM_PAIS`, `NR_POPULACAO`) VALUES ('40', 'CANADA', '37742154');

 /*
 2 ------INSERINDO DADOS NA TABELA EQUIPE-------
 */

INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('70', 'MERCEDES', '30');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('71', 'FERRARI', '31');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('72', 'MCLAREN', '32');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('73', 'MERCEDES', '33');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('74', 'FERRARI', '34');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('75', 'REDE BULL RACING', '35');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('76', 'ALPHATAURI', '36');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('77', 'ALPINE', '37');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('78', 'ALFA ROMEO', '38');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('79', 'FERRARI', '39');
INSERT INTO `estudo`.`tb_equipe` (`ID_EQUIPE`, `NM_EQUIPE`, `ID_PAIS_EQ_(FK)`) VALUES ('80', 'WILLIAMS', '40');

 /*
 3 ------INSERINDO DADOS NA TABELA CIRCUITO-------
 */

INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('20', 'GP DA ÁUSTRIA', '1', '30');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('21', 'GP DA ÁUSTRIA', '2', '31');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('22', 'GP DA ÁUSTRIA', '3', '32');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('23', 'GP DA ÁUSTRIA', '4', '33');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('24', 'GP DA ÁUSTRIA', '5', '34');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('25', 'GP DA ÁUSTRIA', '6', '35');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('26', 'GP DA ÁUSTRIA', '7', '36');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('27', 'GP DA ÁUSTRIA', '8', '37');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('28', 'GP DA ÁUSTRIA', '9', '38');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('29', 'GP DA ÁUSTRIA', '10', '39');
INSERT INTO `estudo`.`tb_circuito` (`ID_CIRCUITO`, `NM_CIRCUITO`, `NR_EXTENSAO`, `ID_PAIS_CI_(FK)`) VALUES ('30', 'GP DA ÁUSTRIA', '11', '40');

 /*
 4 ------INSERINDO DADOS NA TABELA PILOTO-------
 */

INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('80', 'VALTTERI BOTTAS', '1989-08-28', '30', '70');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('81', 'CHARLES LECLERC', '1997-10-19', '31', '71');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('82', 'LANDO NORRIS', '1999-11-13', '32', '72');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('83', 'LEWIS HAMILTON', '1985-01-07', '33', '73');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('84', 'CARLOS SAINZ JR.', '1994-09-01', '34', '74');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('85', 'SERGIO PEREZ', '1990-01-26', '35', '75');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('86', 'PIERRE GASLY', '1996-02-07', '36', '76');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('87', 'ESTEBAN OCON', '1996-09-17', '37', '77');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('88', 'ANTONIO GIOVINAZZI', '1993-12-14', '38', '78');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('89', 'SEBASTIAN VETTEL', '1987-07-03', '39', '79');
INSERT INTO `estudo`.`tb_piloto` (`ID_PILOTO`, `NM_PILOTO`, `DT_NASCIMENTO`, `ID_PAIS_PI_(FK)`, `ID_EQUIPE_PI_(FK)`) VALUES ('90', 'NICHOLAS LATIFI', '1995-06-29', '40', '80');

 /*
 5 ------INSERINDO DADOS NA TABELA PROVA-------
 */

INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('1', '5', 'FINALIZADA', '20');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('2', '6', 'FINALIZADA', '21');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('3', '7', 'FINALIZADA', '22');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('4', '8', 'FINALIZADA', '23');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('5', '9', 'FINALIZADA', '24');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('6', '10', 'FINALIZADA', '25');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('7', '11', 'FINALIZADA', '26');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('8', '12', 'FINALIZADA', '27');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('9', '13', 'FINALIZADA', '28');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('10', '14', 'FINALIZADA', '29');
INSERT INTO `estudo`.`tb_prova` (`ID_PROVA`, `DT_PROVA`, `NM_SITUACAO`, `ID_CIRCUITO_PR_(FK)`) VALUES ('11', '15', 'FINALIZADA', '30');

 /*
 6 ------INSERINDO DADOS NA TABELA RESULTADO-------
 */

INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('1', '80', '1:30\'55.739', '0', '1\'07.657', '77');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('2', '81', '1:30\'58.439', '0', '1\'07.901', '16');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('3', '82', '1:31\'01.230', '0', '1\'07.475', '4');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('4', '83', '1:31\'01.428', '0', '1\'07.712', '44');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('5', '84', '1:31\'04.642', '0', '1\'07.974', '55');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('6', '85', '1:31\'10.831', '0', '1\'08.305', '11');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('7', '86', '1:31\'12.421', '0', '1\'09.025', '10');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('8', '87', '1:31\'13.195', '0', '1\'08.932', '31');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('9', '88', '1:31\'16.885', '0', '1\'08.796', '99');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('10', '89', '1:31\'20.284', '0', '1\'08.623', '5');
INSERT INTO `estudo`.`tb_resultado` (`ID_PROVA_RE_(FK)`, `ID_PILOTO_RE_(FK)`, `NR_TEMPO_PROVA`, `NR_COLECAO_FINAL`, `NR_MELHOR_VOLTA`, `NR_POSICAO_GRID`) VALUES ('11', '90', '1:31\'27.389', '0', '1\'09.662', '6');